env:
  open:

    # API
    DISABLE_API: false
    AUTH_ANONYMOUS_GET: true

    # Storage
    ## DigitalOcean Spaces are Amazon S3 compatible 
    STORAGE: amazon 
    AWS_SDK_LOAD_CONFIG: true
    STORAGE_AMAZON_BUCKET: 
    STORAGE_AMAZON_PREFIX: 
    STORAGE_AMAZON_REGION: us-east-1 # Required to be set to `us-east-1`. Actual region is in the DigitalOcean URL
    STORAGE_AMAZON_ENDPOINT: 

  secret:
    AWS_ACCESS_KEY_ID: 
    AWS_SECRET_ACCESS_KEY: 
    BASIC_AUTH_USER: 
    BASIC_AUTH_PASS: 

# Required to allow Traefik ingress
ingress:
  enabled: false
