{
 "title": "Maestro",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "REST API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Requests per Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(maestro_request_count{}[1m])"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(maestro_request_duration_sum[$__rate_interval]) / rate(maestro_request_duration_count[$__rate_interval])",
     "legendFormat": "Average"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(maestro_request_duration_bucket[$__rate_interval])) by (le))",
     "legendFormat": "95th Percentile"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 10, "y": 1 },
   "targets": [
    {
     "expr": "increase(maestro_server_error_count{}[1m])",
     "legendFormat": "Server Errors (5xx)"
    },
    {
     "expr": "increase(maestro_client_error_count{}[1m])",
     "legendFormat": "Client Errors (4xx)"
    }
   ]
  },
  {
   "title": "Database Calls per Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 14, "y": 1 },
   "targets": [
    {
     "expr": "increase(maestro_db_call_count[1m])"
    }
   ]
  },
  {
   "title": "External API requests per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 1 },
   "targets": [
    {
     "expr": "increase(maestro_apple_music_request_count{job=\"maestro\"}[1m])",
     "legendFormat": "Apple Music"
    },
    {
     "expr": "increase(maestro_spotify_request_count{job=\"maestro\"}[1m])",
     "legendFormat": "Spotify"
    },
    {
     "expr": "increase(maestro_deezer_request_count{job=\"maestro\"}[1m])",
     "legendFormat": "Deezer"
    }
   ]
  },
  { "title": "Process", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(go_memstats_alloc_bytes_total{job=\"maestro\"}[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Total Goroutines",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "go_goroutines{job=\"maestro\"}"
    }
   ]
  }
 ]
}