---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: muse
  namespace: bots
spec:
  selector:
    matchLabels:
      app: muse
  replicas: 1
  template:
    metadata:
      labels:
        app: muse
    spec:
      nodeName: maestro-k8s-prod-pool-cu7ug # Restricting to a specific node, testing to see if it fixes the "couldn't find config" error
      containers:
        - name: muse
          image: codetheweb/muse:latest

          volumeMounts:
            - name: muse-vol
              mountPath: /data

          env:
            - name: DISCORD_TOKEN
              valueFrom:
                secretKeyRef:
                  name: muse-secret
                  key: discord-token

            - name: YOUTUBE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: muse-secret
                  key: youtube-api-key

            - name: SPOTIFY_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: muse-secret
                  key: spotify-client-id

            - name: SPOTIFY_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: muse-secret
                  key: spotify-client-secret

      volumes:
        - name: muse-vol
          persistentVolumeClaim:
            claimName: muse-pvc

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: muse-pv
  namespace: bots
spec:
  storageClassName: do-block-storage
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/muse/"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: muse-pvc
  namespace: bots
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: do-block-storage
