apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: alertmanager-config
  namespace: monitoring
spec:
  receivers:
    - name: 'Discord'
      webhookConfigs:
        - url: 'http://discord-alertmanager-receiver-service:9094'

  route:
    receiver: 'Discord'