---

apiVersion: v1
kind: Secret
metadata:
  name: minialert-secret
  namespace: bots
type: Opaque
stringData:
  discord-bot-token:
  discord-bot-clientid:
  discord-bot-permissions:
  mongo-uri:
  mongo-database-name:

---

apiVersion: v1
kind: Secret
metadata:
  name: minialert-secret-mongo-tls
  namespace: bots
type: Opaque
data:
  tls.crt:
